export interface Unit {
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  category: string;
  categoryColor: 'amber' | 'blue' | 'coral' | 'green' | 'purple';
  description: string;
  available: boolean;
  puzzleId: string;
  gridCol: number;
  gridRow: number;
}

export const UNITS: Unit[] = [
  {
    id: 1,
    slug: 'kinematics',
    title: 'Forward & Inverse Kinematics',
    subtitle: 'How robot arms compute and invert position',
    category: 'Classical Robotics',
    categoryColor: 'amber',
    description: 'Drag a robot arm end-effector and watch the joints solve in real time. Discover the fold point where elbow-up and elbow-down converge.',
    available: true,
    puzzleId: 'fold-point',
    gridCol: 1,
    gridRow: 1,
  },
  {
    id: 2,
    slug: 'pathfinding',
    title: 'Path Planning & Search',
    subtitle: 'A*, Dijkstra, and the cost of shortcuts',
    category: 'Classical Robotics',
    categoryColor: 'blue',
    description: 'Paint terrain, run four algorithms side by side. Find the map where the "obvious" path costs more than going around.',
    available: true,
    puzzleId: 'expensive-shortcut',
    gridCol: 3,
    gridRow: 1,
  },
  {
    id: 3,
    slug: 'slam',
    title: 'SLAM',
    subtitle: 'Map the unknown while finding yourself',
    category: 'Perception',
    categoryColor: 'coral',
    description: 'Drive a robot through fog. Watch uncertainty grow and shrink as landmarks are re-observed. Find the minimum loop closures needed.',
    available: true,
    puzzleId: 'lost-robot',
    gridCol: 5,
    gridRow: 1,
  },
  {
    id: 4,
    slug: 'pid',
    title: 'PID Control',
    subtitle: 'Proportional, integral, derivative feedback',
    category: 'Control Theory',
    categoryColor: 'green',
    description: 'Tune a controller live. Watch overdamped sluggishness, underdamped oscillation, and the satisfying snap of critical damping.',
    available: true,
    puzzleId: 'pid-tune',
    gridCol: 2,
    gridRow: 2,
  },
  {
    id: 5,
    slug: 'sensor-fusion',
    title: 'Sensor Fusion & Kalman Filtering',
    subtitle: 'Combining noisy streams into truth',
    category: 'Perception',
    categoryColor: 'coral',
    description: 'Combine noisy accelerometer and GPS data into a single clean estimate using Bayesian filtering.',
    available: true,
    puzzleId: 'kalman',
    gridCol: 4,
    gridRow: 2,
  },
  {
    id: 6,
    slug: 'dynamics',
    title: 'Robot Dynamics & Trajectories',
    subtitle: 'Newton-Euler equations to smooth motion',
    category: 'Classical Robotics',
    categoryColor: 'amber',
    description: 'From torques to smooth joint-space trajectories. Design a motion that satisfies velocity and acceleration constraints.',
    available: true,
    puzzleId: 'trajectory',
    gridCol: 1,
    gridRow: 3,
  },
  {
    id: 7,
    slug: 'vision',
    title: 'Computer Vision for Robotics',
    subtitle: 'Detection, depth, and visual servoing',
    category: 'Perception',
    categoryColor: 'coral',
    description: 'Object detection and visual servoing: steer a robot toward a target using only camera feedback.',
    available: true,
    puzzleId: 'visual-servo',
    gridCol: 3,
    gridRow: 3,
  },
  {
    id: 8,
    slug: 'swarm',
    title: 'Swarm & Multi-Agent Robotics',
    subtitle: 'Emergent behavior from simple local rules',
    category: 'Advanced',
    categoryColor: 'purple',
    description: 'Simple flocking rules produce rich collective behavior. Find parameters that prevent collision while achieving cohesion.',
    available: true,
    puzzleId: 'flocking',
    gridCol: 5,
    gridRow: 3,
  },
  {
    id: 9,
    slug: 'manipulation',
    title: 'Manipulation & Grasping',
    subtitle: 'Contact mechanics and stable grasps',
    category: 'Classical Robotics',
    categoryColor: 'amber',
    description: 'Plan stable grasps and understand contact mechanics. Find the grasp that maximizes stability against perturbations.',
    available: true,
    puzzleId: 'grasp',
    gridCol: 2,
    gridRow: 4,
  },
  {
    id: 10,
    slug: 'vla',
    title: 'Vision-Language-Action Models',
    subtitle: 'Foundation models for robot action',
    category: 'Foundation AI',
    categoryColor: 'purple',
    description: 'Understand how VLA models unify perception, language, and action. Trace a prompt through the full pipeline.',
    available: true,
    puzzleId: 'vla-trace',
    gridCol: 4,
    gridRow: 4,
  },
  {
    id: 11,
    slug: 'llm-brain',
    title: 'LLM as Robot Brain',
    subtitle: 'Language models for task planning',
    category: 'Foundation AI',
    categoryColor: 'purple',
    description: 'Use structured prompting to break down a high-level task into robot primitives. Find the failure mode in the chain.',
    available: true,
    puzzleId: 'task-chain',
    gridCol: 1,
    gridRow: 5,
  },
  {
    id: 12,
    slug: 'world-models',
    title: 'World Models & Sim-to-Real',
    subtitle: 'Learning latent dynamics, bridging the gap',
    category: 'Foundation AI',
    categoryColor: 'purple',
    description: 'Train a latent world model in sim and see where reality diverges. Quantify the sim-to-real gap.',
    available: true,
    puzzleId: 'sim-real',
    gridCol: 3,
    gridRow: 5,
  },
  {
    id: 13,
    slug: 'edge-ai',
    title: 'Edge AI for Robotics',
    subtitle: 'Inference on device, quantization, accelerators',
    category: 'Systems',
    categoryColor: 'green',
    description: 'Quantize a model and measure the accuracy-latency tradeoff. Find the minimum bit-width that keeps accuracy above threshold.',
    available: true,
    puzzleId: 'quantize',
    gridCol: 5,
    gridRow: 5,
  },
];

export const AVAILABLE_UNITS = UNITS.filter(u => u.available);

export function getUnit(slug: string): Unit | undefined {
  return UNITS.find(u => u.slug === slug);
}
